# Generated by Django 3.1.7 on 2021-10-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Покупатель'), (2, 'Администратор'), (3, 'Кассир'), (4, 'Повар'), (5, 'Курьер')], default=1, verbose_name='Роль пользователя'),
        ),
    ]
